name: fslpython
channels:
 - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/channel
 - defaults
 - conda-forge
dependencies:
 - docopt=0.6.2
 - eddy_qc=1.0.2
 - flake8=3.5.0
 - fmrib-unpack=1.4.1
 - fsleyes=0.30.1
 - fslpy=2.4.0
 - fsl-pyfeeds=0.8.0
 - ipython=7.2.0
 - isodate=0.6.0
 - jinja2=2.10.0
 - jsoncpp=1.8.3
 - lxml=4.2.5
 - matplotlib=3.0.2
 - mkl-service=1.1.2
 - networkx=1.11
 - nibabel=2.3.3
 - numpy=1.15.4
 - pandas=0.24.1
 - paramiko=2.4.2
 - pillow=5.4.1
 - pylint=2.2.2
 - pyparsing=2.2.0
 - python-dateutil=2.7.0
 - python=3.7.3
 - pyyaml=5.1
 - scikit-image=0.14.2
 - scikit-learn=0.20.2
 - scipy=1.2.0
 - seaborn=0.9.0
 - six=1.11.0
 - vtk=8.2.0
 - wxpython=4.0.6
 - pip:
   - nidmfsl
